### PR TITLE
Add nano precision option.

### PR DESCRIPTION
**Pull request by ChrisDev83**
Unsure whether to add test as existing tests dont test the format as it is. Feel free to tweak as needed!

### CODE REVIEW

**Comment by mostafa** [comment]
Hey @ChrisDev83,

Thanks for your contribution! What do you think about making the entire time format optional and including all supported formats?

**Comment by ChrisDev83** [comment]
That would be a better approach, I found the formats odd as I come from "YYYY-mm-dd" world! But definitely more flexible that way.

**Comment by ChrisDev83** [comment]
Actually, I remember why I went against the string format. I felt that given this is for k6 and the test config is written in Javascript, you need to know the format of go date/time format. So you would be supplying a go format in a javascript file. Unless you could allow a javascript date format and have a method to convert that to go format?

**Comment by mostafa** [comment]
@ChrisDev83 Let's keep this as is and open an issue to discuss that. Okay?

**Review by mostafa — APPROVED** [review]

**Comment by ChrisDev83** [comment]
[This current open issue](https://github.com/mostafa/xk6-kafka/issues/260) is related

**Comment by mostafa** [comment]
Released in [v0.24.2](https://github.com/mostafa/xk6-kafka/releases/tag/v0.24.2).

**Comment by mostafa** [comment]
@ChrisDev83 Then, please update it with our discussion.

**Pull request merged**
