### PR TITLE
Update APIs to accept JSON object instead of stringified JSON object

### PR DESCRIPTION
**Pull request by iamelevich**
# Changelog
- writer now get object as a parameter
- Add ability to set batch size

### CODE REVIEW

**Comment by mostafa** [comment]
Hi @iamelevich,

Thanks for your contribution and sorry for the delay! 🙏 I took your idea and applied it also to the reader and I like it. I'd be happy to have your feedback on this. Also, I think this should be fixed in all places including `Auth`.

**Comment by iamelevich** [comment]
@mostafa Looks great)

**Comment by mostafa** [comment]
I also updated authentication `Credentials` and `Configuration` structs to be used to parse an actual JSON object instead of a JSON string.

**Comment by iamelevich** [comment]
@mostafa I see an error when I run this branch:
`There was an error fetching messages: context deadline exceeded`

I think problems can be in default config values. For now unfortunately have no free time, but will I will try to debug it when will have free time.

**Pull request closed without merging**
