### PR TITLE
Use ssl client certs for authentication.

### PR DESCRIPTION
**Pull request by hildebrandttk**

### CODE REVIEW

**Comment by mostafa** [comment]
Hey @hildebrandttk,

Thanks for your contribution. Is this still WIP?

**Comment by mostafa** [comment]
@hildebrandttk Thanks for your contribution! 🙏 I'll take it from here and merge it.

**Comment by mostafa** [comment]
@hildebrandttk's changes fix #24 and the changes I've made fix #28.

**Comment by hildebrandttk** [comment]
:+1:

**Comment by fdahunsibread** [comment]
@hildebrandttk Were you able to connect successfully over TLS?If yes, how did you generate the pem files, please ?

**Pull request merged**
