### PR TITLE
Allow producing messages without specifying a Key

### PR DESCRIPTION
**Pull request by eduardowitter**
According to [1], Keys are optional. With this change, by not setting a
key for a message it will be considered null.

Example:
~~~
        let messages = [
            {
                value: JSON.stringify({
                    firstname: "firstname-" + index,
                    lastname: "lastname-" + index,
                }),
                // Only value is set. The key field is not set.
            },
        ];
        let error = produceWithConfiguration(
            producer,
            messages,
            configuration,
            null, //!< Null for key schema, not used
            valueSchema
        );
~~~

[1]
https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets

### CODE REVIEW

**Comment by mostafa** [comment]
Hey @eduardowitter,

Thanks for your contribution! 🙏 Could you please add or modify one of the test-scripts to showcase this? For example, modify [test_json.js](https://github.com/mostafa/xk6-kafka/blob/master/scripts/test_json.js) and add a messsage with no keys. Or if you prefer, add a new test called `test_no_key.js`.

**Comment by mostafa** [comment]
I tested your code and it seems not to work as expected, as you see below:

incorrect results

But if I explicitly pass `key: null` to JS code, it produces the correct result:

correct results

**Comment by mostafa** [comment]
Adding this to the `has_key` condition would produce null keys:
```go
...
} else {
	kafkaMessages[i].Key = []byte("")
}
```

**Comment by eduardowitter** [comment]
Based on your comments, you're seeing garbage in the key value if key is not specified in .js, correct?
I didn't see this on my tests.

Adding the `else` fixed that, correct? I assumed that not setting `.Key` is equivalent of setting a `null` value.

**Comment by eduardowitter** [comment]
Setting `nil` for `.Key` worked for me. Using `[]byte("")` creates a Key with 0 bytes, which means there's still a Key in the message. To actually produce messages without a `Key`, it looks like `nil` is needed.

Could you please repeat your tests using my last commit?

**Comment by mostafa** [comment]
Same exact result:
result

**Comment by mostafa** [comment]
I think you should revert the last commit, because producing messages using the console producer creates the same gibberish for the key field using this command:
```bash
kafka-console-producer --bootstrap-server 127.0.0.1:9092 --topic xk6_kafka_topic "test"
```
result

So, if it's the correct behavior and the way to store the key field, let's follow it. I also tested passing empty key using this command:
```bash
root@fast-data-dev / $ kafka-console-producer --bootstrap-server 127.0.0.1:9092 --topic xk6_kafka_topic --property parse.key=true --property key.separator=,
>,test
```
and this is the result:
result-empty key

**Review by mostafa — APPROVED** [review]

**Comment by mostafa** [comment]
@eduardowitter Just revert the last commit and it's mergeable.

**Comment by mostafa** [comment]
@eduardowitter Do you want to make any other changes? Or should I merge this?

**Comment by eduardowitter** [comment]
Hi @mostafa . I'm not planning more changes, you can go ahead and merge it. Thanks for helping me out with this and for creating this valuable extension. Keep up the good work.

**Comment by mostafa** [comment]
Thanks @eduardowitter for your contribution! 🙏

**Pull request merged**
